### ISSUE TITLE
Failed test: Op http://www.sint-lievens-houtem.be/subscribe.php kan je enkel een naam ingeven en het formulier verzenden.

### ISSUE THREAD

**Issue by ClompenSander** [ClompenSander/Sessie-testen-Sint-Lievens-Houtem#1]
Op http://www.sint-lievens-houtem.be/subscribe.php kan je enkel een naam ingeven en het formulier verzenden.

T10: Op http://www.sint-lievens-houtem.be/subscribe.php kan je enkel een naam ingeven en het formulier verzenden.
https://sanderclompen.testrail.net/index.php?/tests/view/10

**Comment by ssamyn** [comment]
ok
